### ISSUE TITLE
It doesnot match

### ISSUE THREAD

**Issue by caneraydinbey** [kumlali/tzupdater_2016g_workaround#1]
> root@vegan:/home/vegan/Downloads/tzupdater-2.1.0# java -jar tzupdater.jar -l file:///home/vegan/Downloads/tzdata2016g.tar.gz 
> Using file:///home/vegan/Downloads/tzdata2016g.tar.gz as source for tzdata bundle.
> Error. SHA-512 hash for downloaded bundle does not match expected SHA-512 hash.
> Expected  : 25d33125d34458b7a9af627ec3d47b76b1b1fe90e22bf715d2bc642506f97b2667754b948b010b0e54e36a81907b8003ebe9878c8e1f8bdc2ac70cff5bec834b
> Calculated : 17e8e70806e2f19cb05ea88d5fe46300251a814887adbd19e86a6b4cd4d9136e6f6bd77a8196f07efa3f6e718691d54bd60fb02c933dd915de91eb3ad73cbc32
> Please reference tzupdater README
>

**Comment by kumlali** [comment]
I've just downloaded the files and tried, but everything worked as expected for me. With these files we were able to upgrade all the Java installations on our Windows and Linux servers. 

By the way, you can replace SHA-512 hash in `tzdata2016g.tar.gz.sha512` file with calculated SHA-512 hash seen on your error output.
